Add instructions
JohnPhamous/codecademy-daily-journal pull request #7
Opened 2021-02-20 07:42 UTC by JohnPhamous

2021-02-22 22:58 UTC, nduckwiler requested changes
Overall looks good. Major changes include:
1. Renaming to "Inspirational Homepage", which I think [some people will recognize?](https://lifehacker.com/keep-yourself-motivated-by-setting-an-inspirational-bro-1690887159)
2. Moving API details into their own tasks
3. Using Ben's article and informational where needed
4. Adding additional hints

And one more separate request, @JohnPhamous could you add to the README for this project that explains some of the "new" techniques you used? Things that learners haven't seen before: your `errorReducer` and the `api` directory structure. This will help learners when they download your solution code and compare it to their own.

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Journal
We were thinking Inspirational Homepage. Lmk if you're really against this!

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +For this project, you will build journaling application. This application will interact with different APIs to provide users with a space to write down their thoughts. You can think of this app as a
```suggestion
For this project, you will build an inspirational homepage. This application will interact with different APIs to display the current weather, a background image, and an inspirational quote. It will also provide users with a space to write down their goals for the day. You can think of this app as a fancy todo list with dynamic data. 
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Users can mark thoughts as complete
```suggestion
- Users can write down their goals
- Users can delete goals
- Users can mark goals as complete
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Users can check what the weather is
```suggestion
- Users can check the current weather
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- JavaScript
```suggestion
- JavaScript, including requests to APIs
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Redux Toolkit
```suggestion
- Redux
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Redux Toolkit
Making it a general term; we're assuming that it covers redux, react-redux, and redux-toolkit

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Your application is deployed and accessible by users
```suggestion
- Your application is deployed via Netlify and accessible by users
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Build the application using React and Redux Toolkit
```suggestion
- Build the application using React and Redux
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- Users are shown an inspirational image
```suggestion
- Users are shown an inspirational image
- Users can cycle through multiple fetched images
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +
```suggestion
- Deployment with Netlify

```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +For this particular project, you will be using your own text editor (we suggest [VS Code](https://code.visualstudio.com/download)) and Git version control. If you need help setting up your text edito
```suggestion
For this particular project, you will be using your own text editor (we suggest [VS Code](https://code.visualstudio.com/download)) and Git version control. If you need help setting up your text editor, read our [article about setting up a text editor for web development](https://www.codecademy.com/articles/visual-studio-code). If you need a refresher on how to work with Git for version control, [review the Git lesson](https://www.codecademy.com/learn/learn-git) or look at this [cheat sheet](https://www.codecademy.com/learn/learn-git/modules/learn-git-git-workflow-u/cheatsheet).
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +```
Task should just be "use X api...". Hint includes these three steps and the code snippet

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +const API_URL = `https://quotes.rest/qod?language=en`;
Task should just be "use api...". Hint includes these three steps and the code snippet

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +### Connect your Application with the APIs
Make this three separate tasks. Add those bullets and code snippets to the respective hints you originally provided in the APIs section

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +3. Read their [API documentation](https://openweathermap.org/api) to see which API gives you the data you need
Task should just be "use api". Hint includes these three steps and the code snippet

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +### APIs
In this APIs section, you can just list the recommended APIs with a link to their homepages. Specific implementation instructions can go into tasks

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +### APIs
AKA three tasks, one for each API, code snippets can go in hints

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +You can use the [Unsplash API](https://unsplash.com/developers). Here's how to get started:
Task should just be "use api". Hint includes these three steps and the code snippet

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Set up the folder you created previously to be a Git repository. Push the initial files to a repository on GitHub. You should be consistently committing your changes throughout the project. Make sure
Note explicitly to learners that create-react-app sets up git by default. Eventually we can link to Ben's article (tbd)

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Start building your application with mock data. You should focus on how your components will interact with the data rather than how it will get the data from APIs at this point. Once you've polished
```suggestion
Start building your application with mock data. You should focus on how your components will interact with the data rather than how it will get the data from APIs at this point (that comes in a later task). Remember to build reusable components and to keep your components small.
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Start building your application with mock data. You should focus on how your components will interact with the data rather than how it will get the data from APIs at this point. Once you've polished
It wasn't clear to me whether connecting the APIs was included in this task

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Now that you've built your components, you will want to connect them to the Redux store. Remember to build slices that make sense. Related data should belong in the same slice and actions should desc
```suggestion
Now that you've built your components, you will want to connect them to the Redux store. Related data should belong in the same slice and actions should describe events happening in your application. At this point your application is not connected with the APIs so feel free to set the initial states for the slices to mock data.
```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +
```suggestion

HINT
You'll need at least four slices: one for each API and one for the goals list.

```

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +- You are welcome to use other APIs that are not listed above
Add a hint about recommended folder structure here.

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Congratulations on building your application! Deploy what you've built and share it with the world!
Ask them to use netlify and github here

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +Congratulations on building your application! Deploy what you've built and share it with the world!
Hint will be link Ben's informational (in progress)

2021-02-22 22:58 UTC, nduckwiler commented on instructions.md
> +You've built something amazing! Share it with people, get feedback, and improve it.
Let me check if we are linking to forums here.

2021-02-23 04:31 UTC, JohnPhamous commented
@nduckwiler To clarify about the API stuff:

1. Merge the "API" section with the "Connect your Application with the APIs" section
2. Keep the existing "API" section but only link to the recommended APIs
3. Break the "Connect your Application with the APIs" section in 3 sections. 1 for each API where the hints are the code snippets.

2021-03-01 18:06 UTC, ben-spector-cc commented
@JohnPhamous Do a combination of #2 and #3: Keep the existing "API" section but only link to the recommended APIs and break the "Connect your Application with the APIs" section into 3 section, 1 for each API where the task narrative are the steps for using the API and the hints are the code snippets.

2021-03-02 02:03 UTC, JohnPhamous commented
@ben-spector-cc Updated!

2021-03-04 16:46 UTC, ben-spector-cc approved these changes
Only one comment and then it's ready for Author. Nice work on this John!

2021-03-04 16:46 UTC, ben-spector-cc commented on instructions.md
> +Connect your application with the APIs needed for your features. When interacting with APIs, don't forget to handle the loading and error states.
I'm not sure if this is necessary anymore. I think we can get rid of this task, add a "Connect your Application with the..." to the title of the three API-related tasks, and mention "When interacting with APIs, don't forget to handle the loading and error states".

2021-03-06 02:37 UTC, merged