Design Doc
JohnPhamous/codecademy-daily-journal pull request #9
Opened 2021-03-06 02:51 UTC by JohnPhamous

2021-03-08 16:25 UTC, ben-spector-cc requested changes
This looks great! The only thing I'm wondering is whether or not this should be added to the bottom of the README file. 
* I think the benefit of it being in its own file is that it is a little cleaner. 
* I think the benefit of having it in the README is that it is more likely that the learner will read it (they may not notice this design.md file).

@nduckwiler What do you think?

2021-03-08 21:46 UTC, nduckwiler commented
> This looks great! The only thing I'm wondering is whether or not this should be added to the bottom of the README file.

@ben-spector-cc  and @JohnPhamous I think it should be added to the README. We can also remove a lot of the boilerplate there. In README.md let's have "This project was bootstrapped...", then this new content, then include Available Scripts. Remove Learn More.

2021-03-09 01:55 UTC, JohnPhamous commented
@nduckwiler @ben-spector-cc changes have been made

2021-03-11 17:17 UTC, ben-spector-cc approved these changes

2021-03-11 20:24 UTC, merged